# git url for the source code of the prediction server
url: "http://opentox.org/git/ch/lazar-core.git"
# list of databases for the prediction server (under public/data)
data:
  Carcinogenicity:
    -
      endpoint: Rodent carcinogenicity (multiple sex/species/sites)
      directory: public/data/cpdb/multi_cell_call/
      endpoint_definition_url: "http://www.epa.gov/ncct/dsstox/CentralFieldDef.html#ActivityCategory_MultiCellCall"
      endpoint_definition: 'An assignment of carcinogenic categorical activity based on multicell evidence for or against activity:<br/> <b>active</b>, with more than one TD50 or tumor site listed for carcinogenicity experiment sex/species cells (e.g., liver, lung, or Rat Male, Rat Female, etc);<br/> <b>inactive</b>, with no TD50 or tumor site listed AND more than one "no positive results" entry for carcinogenicity experiment sex/species cells (e.g., Rat Male, Rat Female, etc);' 
      source_url: "http://www.epa.gov/ncct/dsstox/sdf_cpdbas.html"
