# plugins
# put the the plugins, that you are developing here. you will need shell access to push changes back
-
  url: "http://opentox.org/git/ch/opentox-plugin.git"
  path: vendor/plugins/opentox
  install: "rake opentox:install"
  # opentox installs also  openbabel, R and cdk
-
  url: "http://opentox.org/git/ch/lazar-plugin.git"
  path: vendor/plugins/lazar
  install: "rake lazar:program:install"

# external plugins, maybe they should be installed in the future by opentox plugin
-
  url: "git://github.com/lazyatom/engines.git"
  path: vendor/plugins/engines
  tag: "2.1.0"
-
  url: "git://github.com/activescaffold/active_scaffold.git"
  path: vendor/plugins/activescaffold
-
  url: "git://github.com/activescaffold/file_column.git"
  path: vendor/plugins/file_column

-
  url: "git://github.com/rails/exception_notification.git"
  path: vendor/plugins/exception_notification

# data and validation results
- 
  url: "http://opentox.org/git/ch/cpdb-data.git"
  path: public/data/cpdb
  tag: 080429
- 
  url: "http://opentox.org/git/ch/iris-data.git"
  path: public/data/iris
  tag: 080215
- 
  url: "http://opentox.org/git/ch/kazius-data.git"
  path: public/data/kazius
- 
  url: "http://opentox.org/git/ch/fda-human-liver-data.git"
  path: public/data/fda-human-liver
- 
  url: "http://opentox.org/git/ch/fdamdd-data.git"
  path: public/data/fdamdd
  tag: 080215
- 
  url: "http://opentox.org/git/ch/epafhm-data.git"
  path: public/data/epafhm
  tag: 080215

